### ISSUE TITLE
Delphi 10.2.3

### ISSUE THREAD

**Issue by limelect** [antoniojmsjr/IPGeoLocation#1]
Could you plz downgrade to 10.2.3 also.

**Comment by antoniojmsjr** [comment]
Ok, I'm checking...

**Comment by antoniojmsjr** [comment]
@limelect Approved for Delphi Tokyo version 10.2.3

**Comment by limelect** [comment]
Thanks

**Comment by limelect** [comment]
while checking the demo the maps and the location is not correct
Map do not show client

![Screenshot - 17_11_2019 , 08_28_06](https://user-images.githubusercontent.com/4199131/69004007-8b57bb80-0914-11ea-91b8-966f5e7deb2a.png)
![Screenshot - 17_11_2019 , 08_29_08](https://user-images.githubusercontent.com/4199131/69004008-8b57bb80-0914-11ea-88c0-924ddccf6319.png)

**Comment by limelect** [comment]
There is also a difference in location between "ipgeolocatioapi" and  "Ip info"  beside both not being correct  
Others need KEY which is OK

**Comment by antoniojmsjr** [comment]
> There is also a difference in location between "ipgeolocatioapi" and "Ip info" beside both not being correct
> Others need KEY which is OK

@limelect Each provider uses its database to retrieve geo location information, and there may be a slight difference in latitude and longitude results, as well as other information.

**Comment by antoniojmsjr** [comment]
> while checking the demo the maps and the location is not correct
> Map do not show client
> 
> ![Screenshot - 17_11_2019 , 08_28_06](https://user-images.githubusercontent.com/4199131/69004007-8b57bb80-0914-11ea-91b8-966f5e7deb2a.png)
> ![Screenshot - 17_11_2019 , 08_29_08](https://user-images.githubusercontent.com/4199131/69004008-8b57bb80-0914-11ea-88c0-924ddccf6319.png)

There must be a limitation with TWebBrowser, I also have this problem, put in the "Demo" to demonstrate the geo location working.
