### ISSUE TITLE
Fixed rendering of Maps in TWebBrwoser

### ISSUE THREAD

**Issue by antoniojmsjr** [antoniojmsjr/IPGeoLocation#2]
Hi @limelect, I made available a correction for the rendering of the maps in TWebBroser.

![Maps TwebBroser](https://user-images.githubusercontent.com/20980984/73124913-9e73b100-3f7f-11ea-86cf-cbf9e8d318f0.png)

**Comment by limelect** [comment]
Nice. Great.
