### ISSUE TITLE
btnIPExternoClick

### ISSUE THREAD

**Issue by limelect** [antoniojmsjr/IPGeoLocation#3]
While pressing btnIPExternoClick I need a certificate
Any Help how to?
Error getting server cetrtificate

**Comment by antoniojmsjr** [comment]
Hi, do a test using Delphi REST Debugger, I use the same components of the program. If the error continues, send me a print.

![image](https://user-images.githubusercontent.com/20980984/111308842-f107a500-8639-11eb-8bab-0dbaddc12080.png)

**Comment by limelect** [comment]
![image](https://user-images.githubusercontent.com/4199131/111373084-2a74fa80-86a4-11eb-9b66-faab29bd8e39.png)
Nothing, just an error beep
Using D10.2.3
In Chrome it works OK
This what i get in chrome
{"ip":"79.180.49.214"}

**Comment by antoniojmsjr** [comment]
1º If you run Demo.exe does the error occur? (if true, send a print of the error)
2º What version of Windows?
3º Did you run as an administrator?

**Comment by limelect** [comment]
![image](https://user-images.githubusercontent.com/4199131/111434190-eca9bd80-8707-11eb-9059-db7d6dfbd9ec.png)
1. above picture
2. window 7
3. yes

**Comment by limelect** [comment]
![image](https://user-images.githubusercontent.com/4199131/111434550-57f38f80-8708-11eb-82bc-16c3664c1d51.png)

2 and 3 have nothing to do with the application

**Comment by antoniojmsjr** [comment]
Check **SecureProtocols** TLS1, TLS11 and TL1S2.  Changes and tests

![image](https://user-images.githubusercontent.com/20980984/111466847-8bcbb680-8702-11eb-91d7-6ff00ef9362b.png)

**Comment by limelect** [comment]
NO Secure protocol
D10.2.3
![image](https://user-images.githubusercontent.com/4199131/111641160-8f943180-8805-11eb-8335-477c90425117.png)

**Comment by limelect** [comment]
Ok now i have added
uses  System.Net.HttpClient
  rstClientGetIP.SecureProtocols:=[THTTPSecureProtocol.TLS1, THTTPSecureProtocol.TLS11, THTTPSecureProtocol.TLS12];

**Comment by antoniojmsjr** [comment]
Successfully?

**Comment by limelect** [comment]
yes

**Comment by antoniojmsjr** [comment]
About the error

https://stackoverflow.com/questions/55642128/why-i-get-error-security-error-12175-with-tnethttprequest
