### ISSUE TITLE
Server certificate error

### ISSUE THREAD

**Issue by limelect** [antoniojmsjr/IPGeoLocation#4]
Your new ver 1.5.1 on 8.8.8.8 need a server certificate
also on search, your download does not have a library directory
Why do you use GOOGLE? and not my IP?
D10.2.3

**Comment by antoniojmsjr** [comment]
* Certificate: Solution in issue https://github.com/antoniojmsjr/IPGeoLocation/issues/3
*  8.8.8.8 is the default IP if it is not possible to retrieve the external IP.
